application: rmc-room-finder
version: 1
runtime: python27
threadsafe: true
api_version: 1

skip_files:
  - ^(.*/)?\.md.*
  - ^(.*/)?\.scss.*
  - ^\.git/*
  - ^node_modules/*
  - ^(.*/)?\.map.*

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(api|rest)/.*
  script: main.APP

- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app
